options:
  website-database:
    type: string
    default: "mydatabase"
    description: The name of the database to use, if it does not exist it will be created
  website-location:
    type: string
    default: "folder"
    description: describes is the website is on a folder or bzr branch

