#!/bin/sh

set -e
#create directories to store mysql configuration and delete any reused files from previous units.
mkdir -p /var/webconfig
rm -fr /var/webconfig/*
cp ./lib/* /var/webconfig
chown -R www-data:www-data /var/webconfig
juju-log "Installing packages"
apt-get install -y apache2 php5 mysql-client curl php5-mysql php5-mcrypt php5-curl ttf-dejavu-core ucf debconf-utils

# Installing composer globally
juju-log "Installing Composer Package Manager"
curl -s http://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# Installing codeception globally
juju-log "Installing Codeception Testing Framework"
curl -s http://codeception.com/codecept.phar > /usr/local/bin/codecept

# Configure apache
juju-log "Enabling apache modules: rewrite, vhost_alias, php5"
a2enmod rewrite vhost_alias php5

#copy php files to directory
rm -fr /var/www/*
if ls ./website/* > /dev/null 2>&1; then
  cp -r ./website/* /var/www
  chown -R www-data:www-data /var/www
fi

#opening port 80
juju-log "Exposing apache2 service"
open-port 80/tcp